### ISSUE TITLE
on Windows, mlserver raises AttributeError: module 'signal' has no attribute 'SIGQUIT'

### ISSUE THREAD

**Issue by HugoMVale** [SeldonIO/MLServer#1022]
Hello,
I am on Windows with python 3.10.10:
```
(.venv) PS C:\Code\test> python --version
Python 3.10.10
```
and with the following dependencies:
```
(.venv) PS C:\Code\test> pip list
Package            Version
------------------ ---------
aiofiles           23.1.0
aiohttp            3.8.4
aiokafka           0.8.0
aiosignal          1.3.1
anyio              3.6.2
async-timeout      4.0.2
attrs              22.2.0
Brotli             1.0.9
certifi            2022.12.7
cffi               1.15.1
charset-normalizer 3.0.1
click              8.1.3
colorama           0.4.6
fastapi            0.89.1
frozenlist         1.3.3
gevent             22.10.2
geventhttpclient   2.0.2
greenlet           2.0.2
grpcio             1.51.3
h11                0.14.0
idna               3.4
joblib             1.2.0
kafka-python       2.0.2
mlserver           1.2.3
multidict          6.0.4
numpy              1.24.2
orjson             3.8.7
packaging          23.0
pandas             1.5.3
pip                22.3.1
prometheus-client  0.16.0
protobuf           4.22.0
py-grpc-prometheus 0.7.0
pycparser          2.21
pydantic           1.10.5
python-dateutil    2.8.2
python-dotenv      1.0.0
python-rapidjson   1.9
pytz               2022.7.1
scikit-learn       1.2.1
scipy              1.10.1
setuptools         65.5.0
six                1.16.0
sniffio            1.3.0
starlette          0.22.0
starlette-exporter 0.15.1
threadpoolctl      3.1.0
tritonclient       2.31.0
typing_extensions  4.5.0
uvicorn            0.20.0
yarl               1.8.2
zope.event         4.6
zope.interface     5.5.2
```
When I try running `mlserver`, I always get the following error message:
```
(.venv) PS C:\Code\test> mlserver
Traceback (most recent call last):
  File "C:\Users\hugom\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hugom\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Code\test\.venv\Scripts\mlserver.exe\__main__.py", line 4, in <module>
  File "C:\Code\test\.venv\lib\site-packages\mlserver\__init__.py", line 2, in <module>
    from .server import MLServer
  File "C:\Code\test\.venv\lib\site-packages\mlserver\server.py", line 13, in <module>
    from .parallel import InferencePool
  File "C:\Code\test\.venv\lib\site-packages\mlserver\parallel\__init__.py", line 1, in <module>
    from .pool import InferencePool
  File "C:\Code\test\.venv\lib\site-packages\mlserver\parallel\pool.py", line 8, in <module>
    from .model import ParallelModel
  File "C:\Code\test\.venv\lib\site-packages\mlserver\parallel\model.py", line 11, in <module>
    from .dispatcher import Dispatcher
  File "C:\Code\test\.venv\lib\site-packages\mlserver\parallel\dispatcher.py", line 11, in <module>
    from .worker import Worker
  File "C:\Code\test\.venv\lib\site-packages\mlserver\parallel\worker.py", line 24, in <module>
    IGNORED_SIGNALS = [signal.SIGINT, signal.SIGTERM, signal.SIGQUIT]
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```
Is this a known issue?
According to [this](https://github.com/seomoz/qless-py/issues/59) there is no SIGQUIT in Windows...

**Comment by adriangonz** [comment]
Hey @HugoMVale ,

Unfortunately, Windows is not currently supported in MLServer and it's not part of the roadmap.

Most of the team runs Linux - which is also used in most prod envs - so that's the main target that we focus on.

**Comment by adriangonz** [comment]
That's a great shout - thanks for bringing that up @HugoMVale . 

I've opened up #1035 to tackle that, which hopefully should be there by the next release.

**Comment by karthickn210** [comment]
Hi 
I'm just using ML server framing the input data only, as temporary solution I followed the below. At a high level reinstall again will fix the issue.
```py
try:
    from mlserver.codecs import NumpyCodec
    print('Imported')
except Exception as AttributeError:
    import subprocess
    install_cmd = 'pip install mlserver'
    proc = subprocess.Popen(install_cmd,shell=True)
    print('Reinstalled')

finally:
    from mlserver.codecs import NumpyCodec
    print('Imported')
```
Note : This is not a permanent fix, just for solution it may helpful. You can explore or try further in your own way.
