### ISSUE TITLE
Issue in multi model serving

### ISSUE THREAD

**Issue by RoopaSiddaveerappa** [SeldonIO/MLServer#1264]
Hello,

I am trying to implement multi model serving using 
sklearn model and custom model,
when i executed mlserver start . command 
in the console i am getting below error (even after this error  I was able to access only on custom model  related API but not sklearn model)

2023-06-26 21:49:57,280 [mlserver] WARNING - Model name 'numpyro-data' is different than model's folder name 'coustom-model'.
2023-06-26 21:49:57,330 [mlserver.parallel] DEBUG - Starting response processing loop...
2023-06-26 21:49:57,332 [mlserver.rest] INFO - HTTP server running on http://0.0.0.0:8080
INFO:     Started server process [16856]
INFO:     Waiting for application startup.
2023-06-26 21:49:57,355 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:8082
2023-06-26 21:49:57,355 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:8082/metrics
INFO:     Started server process [16856]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2023-06-26 21:49:58,000 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:8081
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
INFO:     Waiting for application shutdown.
INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
INFO:     Application shutdown complete.
ERROR:    Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 161, in startup
    server = await loop.create_server(
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/user/.local/lib/python3.9/site-packages/mlserver/rest/server.py", line 71, in start
    await self._server.serve()
  File "/home/user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "/home/user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 171, in startup
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/starlette/routing.py", line 674, in lifespan
    await receive()
  File "/home/user/.local/lib/python3.9/site-packages/uvicorn/lifespan/on.py", line 139, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError

2023-06-26 21:49:58,584 [mlserver] INFO - Loaded model 'numpyro-data' succesfully.
2023-06-26 21:49:58,654 [mlserver] INFO - Loaded model 'mnist-svm' succesfully.

I tried to change the http port to 8088 and run mlserver but not able to access swagger URI 
Thanks in advance,

**Comment by adriangonz** [comment]
Hey @RoopaSiddaveerappa ,

Your `8080` port is not available (i.e. MLServer's default port):

```
 OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
```

You can change it through MLServer's settings.
