### ISSUE TITLE
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'

### ISSUE THREAD

**Issue by meghanapechetti** [SeldonIO/MLServer#1355]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/mlserver/__init__.py", line 2, in <module>
    from .server import MLServer
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/mlserver/server.py", line 6, in <module>
    from .model import MLModel
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/mlserver/model.py", line 3, in <module>
    from .codecs import (
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/mlserver/codecs/__init__.py", line 1, in <module>
    from .numpy import NumpyCodec, NumpyRequestCodec
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/mlserver/codecs/numpy.py", line 5, in <module>
    from ..types import RequestInput, ResponseOutput, Parameters
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/mlserver/types/__init__.py", line 1, in <module>
    from .dataplane import (
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/mlserver/types/dataplane.py", line 31, in <module>
    class TensorData(BaseModel):
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 99, in __new__
    namespace, config_wrapper.ignored_types, class_vars, base_field_names
  File "/home/krantikavali/chatbot-model-server/venv/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 296, in inspect_namespace
    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
python-BaseException

**Comment by adriangonz** [comment]
Hey @meghanapechetti ,

MLServer `1.0.1` is quite old, so I'd suggest first upgrading to MLServer `1.3.5`.

Feel free to re-open if you still see the same issue after upgrading.
