### ISSUE TITLE
StringCodec not compliant with dataplane.proto -- gRPC failure

### ISSUE THREAD

**Issue by JakeNeyer** [SeldonIO/MLServer#400]
The StringCodec responds with a bytes string instead of an array of byte strings which causes serialization to fail for gRPC requests:

proto:
```
  // Representation for BYTES data type. The size must match what is
  // expected by the tensor's shape. The contents must be the flattened,
  // one-dimensional, row-major order of the tensor elements.
  repeated bytes bytes_contents = 8;

```

```
    def encode(cls, name: str, payload: List[str]) -> ResponseOutput:
        packed, shape = pack(map(_encode_str, payload))
        return ResponseOutput(
            name=name,
            datatype="BYTES",
            shape=shape,
            data=packed,
        )

```

Throws: 
```
ERROR:grpc._cython.cygrpc:Unexpected [TypeError] raised by servicer method [/inference.GRPCInferenceService/ModelInfer]
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 680, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 794, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 545, in _handle_unary_unary_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 402, in _finish_handler_with_unary_response
  File "/Users/jacobneyer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/mlserver/grpc/servicers.py", line 26, in _inner
    return await f(self, request, context)
  File "/Users/jacobneyer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/mlserver/grpc/servicers.py", line 82, in ModelInfer
    response = ModelInferResponseConverter.from_types(result)
  File "/Users/jacobneyer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/mlserver/grpc/converters.py", line 310, in from_types
    for output in type_object.outputs
  File "/Users/jacobneyer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/mlserver/grpc/converters.py", line 310, in <listcomp>
    for output in type_object.outputs
  File "/Users/jacobneyer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/mlserver/grpc/converters.py", line 345, in from_types
    type_object.data, datatype=type_object.datatype
  File "/Users/jacobneyer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/mlserver/grpc/converters.py", line 291, in from_types
    return pb.InferTensorContents(**contents)
TypeError: 123 has type int, but expected one of: bytes
```

While 
```
    def encode(cls, name: str, payload: List[str]) -> ResponseOutput:
        packed, shape = pack(map(_encode_str, payload))
        return ResponseOutput(
            name=name,
            datatype="BYTES",
            shape=shape,
            data=[packed],
        )
```

serializes the response correctly

**Comment by iamahern** [comment]
I came across the same issue as well attempting to use the StringCodec to encode response data. I included an example of calling the gRPC endpoint for a model passing a string input in the Juypter Notebook included https://github.com/SeldonIO/MLServer/pull/402. The example utilizes data packing as describe in this defect in order to correctly function in a gRPC context.

**Comment by JakeNeyer** [comment]
@iamahern / @adriangonz  FWIW, I wrote a JSON codec if you'd be interested in it. I used a custom encoder for any nested numpy types that we ran up against (probably can/should be extended)

```
def serialize(content):
    return json.dumps(
        content,
        ensure_ascii=False,
        allow_nan=False,
        indent=None,
        separators=(",", ":"),
        cls=NumpyEncoder,
    )


class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, np.float32):
            return str(obj)
        return json.JSONEncoder.default(self, obj)


class JSONCodec(InputCodec):
    ContentType = "json"

    @classmethod
    def encode(cls, name: str, payload: str) -> ResponseOutput:
        data = serialize(payload)

        return ResponseOutput(
            name=name,
            shape=(1, len(data)),
            datatype="BYTES",
            data=[bytes(data.encode())],
        )
```

**Comment by adriangonz** [comment]
Nice one @JakeNeyer, thanks for sharing!

A JSON codec would be an amazing addition! I'm wondering whether it would make sense to bundle it alongside the, currently MLflow-specific, [`TensorDictCodec`](https://github.com/SeldonIO/MLServer/blob/65b38293acc4c4d35a1fc7c6187abb6d506a1181/runtimes/mlflow/mlserver_mlflow/codecs.py#L8-L16)? This would also give users the ability to use a JSON codec at the request-level, so that each input entry gets translated into a key / value pair on the decoded JSON dict. 

In fact, both the input-level and request-level JSON codecs could get combined so that a request input like the one below: 

```json
{
	"parameters": {
		"content_type": "json"
	},
	"inputs": [
		{
			"name": "input-1",
			"parameters": {
				"content_type": "np"
			},
			"datatype": "INT32",
			"shape": [3],
			"data": [1, 2, 3]
		},
		{
			"name": "input-2",
			"parameters": {
				"content_type": "json"
			},
			"datatype": "BYTES",
			"shape": [1],
			"data": ["{\"foo\": \"bar\"}"]
		}
	]
}
```

could be decoded as this dict:

```python
{
	"input-1": np.array([1, 2, 3]),
	"input-2": {
		"foo": "bar"
	}
}
```

What are your thoughts on the above?

**Comment by JakeNeyer** [comment]
@adriangonz, I like this idea! Happy to help implement!
