### ISSUE TITLE
UnicodeDecodeError when returning a string value from MLFLow Model running in MLServer

### ISSUE THREAD

**Issue by deadl0ck** [SeldonIO/MLServer#484]
This is quite similar to the issue described in #162 except in this case the error is when a string value is being returned from the inference request.

I built a simple test model using the publicly available Iris data, and packaged it as an MLFlow Model and and I am trying to call it using MLServer.

Here is a sample of the input data printed out from the code:

```
sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
```

The `species` is what should be returned - and it is returned fine if the model is loaded and called directly in python.

I get the decode error when the model is called when deployed in MLServer.
My Model signature (as reported in my model registry) is:
```
signature:
  inputs: '[{"name": "sepal_length", "type": "double"}, {"name": "sepal_width", "type":
    "double"}, {"name": "petal_length", "type": "double"}, {"name": "petal_width",
    "type": "double"}]'
  outputs: '[{"type": "string"}]'
```
  
If I rebuild the model so that it returns an integer instead of a string (and change the training data accordingly) it works fine.

Here is a sample of the input data (I have tried MANY variations of this to see if I could get it working):
```
{
    "inputs": [
        {
            "data": [
                5.0
            ],
            "datatype": "FP32",
            "name": "sepal_length",
            "shape": [
                1
            ]
        },
        {
            "data": [
                3.5
            ],
            "datatype": "FP32",
            "name": "sepal_width",
            "shape": [
                1
            ]
        },
        {
            "data": [
                1.3
            ],
            "datatype": "FP32",
            "name": "petal_length",
            "shape": [
                1
            ]
        },
        {
            "data": [
                0.3
            ],
            "datatype": "FP32",
            "name": "petal_width",
            "shape": [
                1
            ]
        }
    ],
    "parameters": {
        "content_type": "pd"
    }
}
```

Here is the full error:

```
Response Status: 500
Response Reason: Internal Server Error
Response Text  :
Traceback (most recent call last):
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/starlette_exporter/middleware.py", line 135, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/mlserver/rest/app.py", line 27, in custom_route_handler
    return await original_route_handler(request)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/routing.py", line 243, in app
    is_coroutine=is_coroutine,
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/routing.py", line 148, in serialize_response
    return jsonable_encoder(response_content)
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/encoders.py", line 71, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/encoders.py", line 107, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/encoders.py", line 124, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/encoders.py", line 107, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/encoders.py", line 124, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/Users/deadlock/git/mlserver-test/HWMM/hwmm/lib/python3.7/site-packages/fastapi/encoders.py", line 130, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic/json.py", line 52, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
```

**Comment by adriangonz** [comment]
Hey @deadl0ck , 

Thanks for raising this one. Based on what you describe, it seems we may need to extend the work added in #273 to also encode other types of outputs, like strings. Just for explicitness, this is also related to #425. Ideally, we should find a unified way to handle arbitrary return types across all runtimes.

**Comment by MarcinSkrobczynski** [comment]
Hi @adriangonz 

I had a similar issue, when we could expect a fix for that?
