### ISSUE TITLE
Spacy generated model does not provide python_function flavor

### ISSUE THREAD

**Issue by MarcinSkrobczynski** [SeldonIO/MLServer#505]
I took an example from the mlflow from [here](https://github.com/mlflow/mlflow/tree/master/examples/spacy).

It generates the following `MLModel`:
```
artifact_path: model
flavors:
  spacy:
    data: model.spacy
    spacy_version: 2.3.7
model_uuid: a09fd277615b41f7bc018337dc0e1e91
run_id: 06999cc3b01643248639a4c997a21253
utc_time_created: '2022-02-28 10:51:15.936127'
```

After I am trying to run it I have the following error: `mlflow.exceptions.MlflowException: Model does not have the "python_function" flavor`

with traceback:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/bin/mlserver", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver/cli/main.py", line 76, in main
    root()
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver/cli/main.py", line 19, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver/cli/main.py", line 43, in start
    await server.start(models_settings)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver/server.py", line 54, in start
    for model_settings in models_settings
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver/registry.py", line 249, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver/registry.py", line 137, in load
    await self._load_model(new_model)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver/registry.py", line 146, in _load_model
    await model.load()
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlserver_mlflow/runtime.py", line 117, in load
    self._model = mlflow.pyfunc.load_model(model_uri)
  File "/root/miniconda3/envs/mlflow-52feda616e2f27e04d1073127b9dc8bd354b34d5/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 674, in load_model
    RESOURCE_DOES_NOT_EXIST,
```

Is it needed to have `python_function` flavor?
If I add it by hand, I have:
```
OSError: [E053] Could not read config file from (...)/mlruns/0/06999cc3b01643248639a4c997a21253/artifacts/model/model.spacy/config.cfg
```

**Comment by adriangonz** [comment]
Hey @MarcinSkrobczynski ,

That's a great point.

At the moment, only the `python_function` _flavour_ of MLflow is supported within MLServer. Is it possible to log the model from MLflow with this flavour added on top?

**Comment by adriangonz** [comment]
Is there any chance that it's changed in recent versions of MLflow? Looking at [their docs](https://www.mlflow.org/docs/latest/models.html#spacy-spacy), they claim that:

> The spaCy model flavor enables logging of [spaCy models](https://spacy.io/models) in MLflow format via the [mlflow.spacy.save_model()](https://www.mlflow.org/docs/latest/python_api/mlflow.spacy.html#mlflow.spacy.save_model) and [mlflow.spacy.log_model()](https://www.mlflow.org/docs/latest/python_api/mlflow.spacy.html#mlflow.spacy.log_model) methods. Additionally, these **methods add the python_function flavor to the MLflow Models that they produce**, allowing the models to be interpreted as generic Python functions for inference via [mlflow.pyfunc.load_model()](https://www.mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.load_model).

**Comment by MarcinSkrobczynski** [comment]
OK, but I used the same instruction they mentioned:
```python
mlflow.spacy.log_model(spacy_model=nlp, artifact_path="model")
```
and there is no python_function flavor :sweat_smile:

**Comment by adriangonz** [comment]
Mmmh that's strange. Would it be worth raising this on the MLflow community? According to their docs, there should be a `python_function` flavour, so maybe there's something weird going on there?

**Comment by MarcinSkrobczynski** [comment]
During my investigation I observed that this is a problem with their example (`mlflow`) using spacy.
I think we can close it.
