### ISSUE TITLE
What is payload to be passed for string to be inferenced?

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [SeldonIO/MLServer#545]
I am confused on how to pass inference request for a string object in MLServer. I am passing currently my inference requests as the following:

```json
inference_request = {
    "id": "translation_request",
    "inputs": [
        {
            "id": "request-1",
            "name": "text",
            "datatype": "BYTES",
            "data":"Today",
            "shape": [5]
        }
    ],
}
```

This is the inference code I have used named in a file called `inference.py`:
```code
import requests

# Inference_request above was defined in this line

endpoint = "http://localhost:8080/v2/models/enmltranslation/infer"
response = requests.post(endpoint, json=inference_request)
print(response)
```

My ML server model is as follows:

```code
from transformers import AutoTokenizer
from transformers import AutoModelForSeq2SeqLM
from transformers import pipeline
from mlserver import MLModel
from mlserver import types
from mlserver.types import InferenceRequest, InferenceResponse



class Enmltrans(MLModel):
    async def load(self, model_name="Helsinki-NLP/opus-mt-en-ml"):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        self.translator = pipeline(
            "translation", model=self.model, tokenizer=self.tokenizer
        )

        self.ready = True
        return self.ready
 
    async def predict(self, payload):
        try:
            for inp in payload.inputs:
                sample_text = inp.data
                output = self.translator(sample_text)
                translation = output[0]["translated_text"]
                
                assert inp.id == "request-1"
                return types.InferenceResponse(
                id=payload.id,
                model_name=self.name,
                model_version=self.version,
                outputs=[
                    types.ResponseOutput(
                        name="translated_text", datatype="BYTES", data=translation
                    )
                ],
                )
        except Exception as e:
            return {"errors": e.args[0]}
```

When running the command `mlserver start .` and running `inference.py`. I am getting the below error which is quite confusing to me:

```Traceback (most recent call last):
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette_exporter/middleware.py", line 135, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/mlserver/rest/app.py", line 27, in custom_route_handler
    return await original_route_handler(request)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/mlserver/rest/endpoints.py", line 59, in infer
    inference_response = await self._data_plane.infer(
  File "/home/kurianbenoy/MLServer/microservice-ai-en_ml_translation_mlserver/env/lib/python3.8/site-packages/mlserver/handlers/dataplane.py", line 63, in infer
    prediction.id = payload.id
AttributeError: 'dict' object has no attribute 'id'
```

**Comment by adriangonz** [comment]
Hey @kurianbenoy-sentient , 

Thanks for sharing all that extra detail. That definitely helps when answering these types of issues.

My guess is that the problem comes from the `except` block in your custom code, where you return a dictionary. Instead, the `predict()` method **must always** return an `InferenceResponse` object (since that's what's expected upstream). For cases where you want to raise an error, you can **raise an exception** from the [`MLServerError` class](https://github.com/SeldonIO/MLServer/blob/9358dd2de7e309471c2382364289d56f000be6fe/mlserver/errors.py#L4-L7) hierarchy. This exception will get handled accordingly, returning the right HTTP error code, as well as the right message, back to the client.

For example, in your case this could look like:

```python
from transformers import AutoTokenizer
from transformers import AutoModelForSeq2SeqLM
from transformers import pipeline
from mlserver import MLModel
from mlserver import types
from mlserver.types import InferenceRequest, InferenceResponse
from mlserver.errors import MLServerError



class Enmltrans(MLModel):
    async def load(self, model_name="Helsinki-NLP/opus-mt-en-ml"):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        self.translator = pipeline(
            "translation", model=self.model, tokenizer=self.tokenizer
        )

        self.ready = True
        return self.ready
 
    async def predict(self, payload):
        try:
            for inp in payload.inputs:
                sample_text = inp.data
                output = self.translator(sample_text)
                translation = output[0]["translated_text"]
                
                assert inp.id == "request-1"
                return types.InferenceResponse(
                id=payload.id,
                model_name=self.name,
                model_version=self.version,
                outputs=[
                    types.ResponseOutput(
                        name="translated_text", datatype="BYTES", data=translation
                    )
                ],
                )
        except Exception as e:
			raise MLServerError(msg=e.args[0])
```

Could you try this out @kurianbenoy-sentient ?

**Comment by kurianbenoy-sentient** [comment]
@adriangonz I tried with code you shared with following inference script:

```code
"""Inference model"""
import requests

inference_request = {
    "id": "request-1",
    "inputs": [
        {
            "id": "request-1",
            "name": "text",
            "datatype": "BYTES",
            "data": "Today is a great day",
            "shape": [0],
        }
    ],
}

endpoint = "http://localhost:8080/v2/models/enmltranslation/infer"
response = requests.post(endpoint, json=inference_request)
print(response.json())
```

I am getting a `500 internal server error` with following logs as shown [in link](https://gist.github.com/kurianbenoy-sentient/e3d7d163b2575c12d4387cff422f6ec2)

**Comment by adriangonz** [comment]
@kurianbenoy-sentient is there any chance that you're setting the `status_code` kwarg of `MLServerError` as `None`? The error from that stacktrace seems to suggest that. Alternatively, you can play around with the `MLServerError` class, and even extend it to create your own.

The key point is that errors should be raised as exceptions, and that the `predict` method should always return an `InferenceResponse` object.

**Comment by kurianbenoy-sentient** [comment]
I was facing the same issue when I tried this [tutorial also](https://mlserver.readthedocs.io/en/latest/examples/custom-json/README.html). Then I realized the issue was with my dependencies and on a fresh install of mlserver it downgraded starlette from 0.19 to 0.17.1. This resulted in fixing my code after following the steps @adriangonz mentioned.

The final code can be found here:

```py
"""Translation model - Inference class - seldon MLServer"""
import json

from transformers import AutoTokenizer
from transformers import AutoModelForSeq2SeqLM
from transformers import pipeline
from mlserver import MLModel
from mlserver import types
from mlserver.codecs import StringCodec
from mlserver.types import InferenceRequest, InferenceResponse
from mlserver.errors import MLServerError


class Enmltrans(MLModel):
    async def load(self, model_name="Helsinki-NLP/opus-mt-en-ml"):
        print("Initialize model")
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        self.translator = pipeline(
            "translation", model=self.model, tokenizer=self.tokenizer
        )

        self.ready = True
        print("model is ready")
        return self.ready

    async def predict(self, payload):
        try:
            inputs = {}
            for inp in payload.inputs:
                inputs[inp.name] = json.loads(
                    "".join(self.decode(inp, default_codec=StringCodec))
                )
            sample_text = inputs["echo"]["text"]
            output = self.translator(sample_text)
            translation = output[0]["translation_text"]

            return types.InferenceResponse(
                id=payload.id,
                model_name=self.name,
                model_version=self.version,
                outputs=[
                    types.ResponseOutput(
                        name="translated_text",
                        datatype="BYTES",
                        data=[translation],
                        shape=[len(translation)],
                        parameters=types.Parameters(content_type="str"),
                    )
                ],
            )
        except Exception as e:
            raise MLServerError(msg=e.args[0])


```

**Comment by adriangonz** [comment]
That's really interesting @kurianbenoy-sentient! Thanks for sharing what solved it for you.
