### ISSUE TITLE
NotImplementedError while building custom serving runtime.

### ISSUE THREAD

**Issue by MLHafizur** [SeldonIO/MLServer#743]
I am building  a custom runtime for my PyTorch model.  To build the runtime, I had to import some modules list:

```
from multi_classification import predict, prepare_dataset
from classification import process_adverse_types_categories
```
Also I need to keep a modeling folder in the same direction of the runtime to load the pytorch model correctly. So putting all of the dependent modules and folder where the `model-settings.json` and other configuration file located, But when I am trying to run `mlserver start .`  I am getting  the `NotImplementedError`:

```
2022-09-25 19:03:41,539 [mlserver] WARNING - Model name 'multiclass-En' is different than model's folder name '.'.
Traceback (most recent call last):
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\Scripts\mlserver.exe\__main__.py", line 7, in <module>
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\mlserver\cli\main.py", line 76, in main
    root()
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\mlserver\cli\main.py", line 19, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\mlserver\cli\main.py", line 43, in start
    await server.start(models_settings)
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\mlserver\server.py", line 42, in start
    self._add_signal_handlers()
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\site-packages\mlserver\server.py", line 76, in _add_signal_handlers
    loop.add_signal_handler(sign, lambda: asyncio.ensure_future(self.stop()))
  File "C:\Users\hafizur.rahman\Anaconda3\envs\modelmesh\lib\asyncio\events.py", line 539, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

**Comment by adriangonz** [comment]
Hey @MLHafizur ,

This looks like a Windows specific issue. Unfortunately we don't support development in Windows.

A potential alternative could be to run your custom runtime within a Docker image (e.g. using the [`mlserver build` subcommand](https://mlserver.readthedocs.io/en/latest/user-guide/custom.html#building-a-custom-mlserver-image)).
