### ISSUE TITLE
Rasing an exception during load of a model.py custom model shuts down processing loop

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/MLServer#881]
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 140, in _process_model_update
    await self._model_registry.load(model_settings)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 273, in load
    return await self._models[model_settings.name].load(model_settings)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 141, in load
    await self._load_model(new_model)
  File "/opt/conda/lib/python3.8/site-packages/mlserver/registry.py", line 157, in _load_model
    await model.load()
  File "/mnt/agent/models/choice-is-two_1/1/model.py", line 25, in load
    raise ModelParametersMissing(self.name, "no settings.parameters.extra.init_parameters found")
model.ModelParametersMissing: Parameters missing for model choice-is-two_1 no settings.parameters.extra.init_parameters found
2022-12-03 16:11:47,354 [mlserver.parallel] ERROR - Response processing loop crashed. Restarting the loop...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 40, in _process_responses_cb
    process_responses.result()
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/dispatcher.py", line 54, in _process_responses
    response = await loop.run_in_executor(self._executor, self._responses.get)
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() missing 1 required positional argument: 'reason'
```

**Comment by cliveseldon** [comment]
The above error happened during a grpc loadModel call and that loadModel call did not return with an error but was left waiting (presently no timeout).

**Comment by adriangonz** [comment]
Just as an update on this one, this seems to be an edge case triggered by raising custom exceptions. It doesn't affect regular exceptions (e.g. like `MLServerError`), or custom exceptions built within a custom image, but rather exceptions defined in [custom code loaded on-the-fly](https://mlserver.readthedocs.io/en/latest/user-guide/custom.html#loading-a-custom-mlserver-runtime).

It's quite a strange one. I think the best fix would be to stop propagating exceptions from the parallel workers back to the main process. We can log the stacktrace and original exception on the workers, but then just return a dummy exception with the message (and status code, if it inherits from `MLServerError`).

**Comment by adriangonz** [comment]
Looking a bit more into this one, it may be an issue with how [`__reduce__` is implemented for exceptions](https://stackoverflow.com/a/49715949/5015573) (and nothing to do with custom exceptions). The workaround added in #891 should work anyway though.
