### ISSUE TITLE
Unable to build custom image in Jenkins

### ISSUE THREAD

**Issue by deepanshuhardaha** [SeldonIO/MLServer#951]
Hi,
I am trying to build the custom image in Jenkins and followed the following steps

First, I created an image where MLServer and Docker are installed using the following instructions
```
FROM ubuntu:20.04

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.8-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :
RUN python3.8 -m venv /venv
ENV PATH=/venv/bin:$PATH

RUN set -eux; \
    apt-get update; \
    apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y \
    gnupg-agent \
    apt-transport-https \
    software-properties-common

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
RUN apt-get update
RUN apt-cache policy docker-ce
RUN apt-get install -y docker-ce

RUN pip install mlserver==1.2.0
```

In Jenkins, I am using the above built image as a **builder** and `docker:18.05-dind` as **dind**. This is the content of the Jenkinsfile
```
environment {
    IMAGE_ID = "custom-model-image"
    DOCKER_REPO = "asia.gcr.io/<dummy-gcr-account-name>"
  }

  stages {
    stage('docker login') {
      steps {
        container('builder') {
            sh 'cat /root/.gcp/jenkins-secrets.json | docker login -u _json_key --password-stdin https://asia.gcr.io'
        }
      }
    }

    stage('build') {
      steps {
        container('builder') {
          dir('resources/images'){
            sh "docker pull $DOCKER_REPO:latest || true"
            sh "mlserver build . --tag $IMAGE_ID"
          }
        }
      }
    }

    stage('push') {
      when {
        anyOf {
          branch 'master'
        }
      }
      steps {
        container('builder') {
          sh "docker push $IMAGE_ID:latest"
        }
      }
    }
  }
```

When I try to run the above Jenkins pipeline, I get the following error
```
+ mlserver build . --tag custom-model-image
2023-01-13 18:56:48,094 [mlserver] INFO - Using asyncio event-loop policy: uvloop
2023-01-13 18:56:48,095 [mlserver] INFO - Building Docker image with tag custom-model-image
2023-01-13 18:56:48,096 [mlserver] INFO - Writing Dockerfile in /tmp/tmpaotljtdc/Dockerfile
2023-01-13 18:56:48,096 [mlserver] INFO - Writing .dockerignore in /tmp/tmpaotljtdc/Dockerfile.dockerignore
buildkit not supported by daemon
Traceback (most recent call last):
  File "/venv/bin/mlserver", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/mlserver/cli/main.py", line 263, in main
    root()
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/mlserver/cli/main.py", line 23, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/venv/lib/python3.8/site-packages/mlserver/cli/main.py", line 60, in build
    build_image(folder, dockerfile, tag, no_cache=no_cache)
  File "/venv/lib/python3.8/site-packages/mlserver/cli/build.py", line 54, in build_image
    subprocess.run(build_cmd, check=True, shell=True, env=build_env)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker build --rm . -f /tmp/tmpaotljtdc/Dockerfile -t custom-model-image' returned non-zero exit status 1.
```
 Can someone please point out, what I am doing wrong here?

**Comment by deepanshuhardaha** [comment]
This is the new error I got when I tried `docker:18.09.7-dind`
```
+ mlserver build . --tag holmes-catboost-model-server
2023-01-16 05:56:03,691 [mlserver] INFO - Using asyncio event-loop policy: uvloop
2023-01-16 05:56:03,693 [mlserver] INFO - Building Docker image with tag holmes-catboost-model-server
2023-01-16 05:56:03,693 [mlserver] INFO - Writing Dockerfile in /tmp/tmpy4uigrs5/Dockerfile
2023-01-16 05:56:03,694 [mlserver] INFO - Writing .dockerignore in /tmp/tmpy4uigrs5/Dockerfile.dockerignore
#1 [internal] load .dockerignore
#1 sha256:ba1011dd5f9f87a51dadd6fe89f4bc828ab9cee043547ca589cc4a94ec1b5501
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 sha256:11c5ad125eab5fa31c2489bdd185d54048eac8f6ae992e822cc0bd69705803ff
#2 transferring dockerfile: 1.87kB done
#2 DONE 0.0s
failed to create LLB definition: Dockerfile parse error line 5: ARG requires exactly one argument
Traceback (most recent call last):
  File "/venv/bin/mlserver", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/mlserver/cli/main.py", line 263, in main
    root()
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/mlserver/cli/main.py", line 23, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/venv/lib/python3.8/site-packages/mlserver/cli/main.py", line 60, in build
    build_image(folder, dockerfile, tag, no_cache=no_cache)
  File "/venv/lib/python3.8/site-packages/mlserver/cli/build.py", line 54, in build_image
    subprocess.run(build_cmd, check=True, shell=True, env=build_env)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker build --rm . -f /tmp/tmpy4uigrs5/Dockerfile -t holmes-catboost-model-server' returned non-zero exit status 1.
```

**Comment by adriangonz** [comment]
Hey @deepanshuhardaha ,

From the logs you've shared, I can see these two errors:

- `buildkit not supported by daemon` 
- `failed to create LLB definition: Dockerfile parse error line 5: ARG requires exactly one argument`

Both suggest that you're using an old version of Docker, so I'd advise you to upgrade to a more recent one.
