### ISSUE TITLE
MLServer sub processes may crash (OOM) when given large images. Process Pool stays in broken state.

### ISSUE THREAD

**Issue by ajsalow** [SeldonIO/MLServer#991]
When I send a large image I get the following:

```bash
Traceback (most recent call last):
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette_exporter/middleware.py", line 289, in __call__
    await self.app(scope, receive, wrapped_send)
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/my_runtime/.venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/my_runtime/.venv/lib/python3.8/site-packages/mlserver/rest/app.py", line 27, in custom_route_handler
    return await original_route_handler(request)
  File "/my_runtime/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/my_runtime/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/my_runtime/.venv/lib/python3.8/site-packages/mlserver/rest/endpoints.py", line 52, in infer
    return await self._data_plane.infer(payload, model_name, model_version)
  File "/my_runtime/.venv/lib/python3.8/site-packages/mlserver/handlers/dataplane.py", line 60, in infer
    prediction = await model.predict(payload)
  File "/my_runtime/.venv/lib/python3.8/site-packages/mlserver/parallel.py", line 117, in _inner
    return await pool.predict(payload)
  File "/my_runtime/.venv/lib/python3.8/site-packages/mlserver/parallel.py", line 88, in predict
    return await loop.run_in_executor(self._executor, _mp_predict, payload)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 783, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 629, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
```

The process pool is then corrupted and any subsequent requests also fail but MLServer/the model never report unhealthy.

It would be nice to confirm the process was OOM killed log that, and then start reporting unhealthy so when running at k8s the broken pod can be restarted.

**Comment by adriangonz** [comment]
Hey @ajsalow ,

Based on the logs, this looks like a really old version of MLServer. 

Could you update to the latest version (`1.2.3` as of today) and re-run your example? Feel free to reopen if there's still an issue after upgrading.
