### ISSUE TITLE
How to batch huggingface requets?

### ISSUE THREAD

**Issue by ajsalow** [SeldonIO/MLServer#993]
There doesn't seem to be good documentation around batching huggingface inference requests.

I am trying to follow the [GPU section of the readme](https://github.com/SeldonIO/MLServer/blob/master/docs/examples/huggingface/README.md?plain=1#L280).

I start the server
```
docker run  -p 8080:8080  -e MLSERVER_MODEL_NAME="transformer" -e MLSERVER_MODEL_IMPLEMENTATION="mlserver_huggingface.HuggingFaceRuntime" -e MLSERVER_MODEL_EXTRA="{\"task\":\"text-generation\", \"device\": -1, \"batch_size\":2}" 724664234782.dkr.ecr.us-east-1.amazonaws.com/library/mlserver:huggingface-master-7e6f944
```

Send the request 
```python
inference_request = {
    "inputs": [
        {
          "name": "text_inputs",
          "shape": [1],
          "datatype": "BYTES",
          "data": ["This is a generation for the work" for i in range(2)],
        }
    ]
}

r = requests.post("http://localhost:8080/v2/models/transformer/infer", json=inference_request)
```
and get a 500 response. The logs of the server show

```
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1080, in run_single
    model_inputs = self.preprocess(inputs, **preprocess_params)
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/text_generation.py", line 206, in preprocess
    prefix + prompt_text, padding=False, add_special_tokens=False, return_tensors=self.framework
TypeError: can only concatenate str (not "TensorData") to str
INFO:     172.17.0.1:54364 - "POST /v2/models/transformer/infer HTTP/1.1" 500 Internal Server Error
```

I then try updating the shape of the request because that is shown[ in this test](https://github.com/SeldonIO/MLServer/blob/0b87852f80ec6250c5c5bd42b474220fc790da30/runtimes/huggingface/tests/test_codecs/test_base.py#L35) but get the same thing - `TypeError: can only concatenate str (not "TensorData") to str`

Additionally it's not clearly when to used "args" for the "name" field vs "text_inputs" vs something like shown in the test. 
```
inference_request = {
    "inputs": [
        {
          "name": "args",
          "shape": [2, 1],
          "datatype": "BYTES",
          "data": ["This is a generation for the work" for i in range(2)],
        }
    ]
}
```
Results in
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 122, in _process_request
    return_value = await method(*request.method_args, **request.method_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mlserver_huggingface/runtime.py", line 96, in predict
    prediction = self._model(*args, **kwargs)
TypeError: __call__() takes 2 positional arguments but 3 were given
```

but if I'm not batching it get a 200 with "args"
```
inference_request = {
    "inputs": [
        {
          "name": "args",
          "shape": [1],
          "datatype": "BYTES",
          "data": ["This is a generation for the work"],
        }
    ]
}
```

What's more confusing, is I get different results when using a token classification model

```
docker run  -p 8080:8080  -e MLSERVER_MODEL_NAME="transformer" -e MLSERVER_MODEL_IMPLEMENTATION="mlserver_huggingface.HuggingFaceRuntime" -e MLSERVER_MODEL_EXTRA="{\"task\":\"token-classification\",\"pretrained_model\":\"cmarkea/distilcamembert-base-ner\", \"device\": -1, \"batch_size\":2}" 724664234782.dkr.ecr.us-east-1.amazonaws.com/library/mlserver:huggingface-master-7e6f944
```

```
inference_request = {
    "inputs": [
        {
          "name": "text_inputs",
          "shape": [1],
          "datatype": "BYTES",
          "data": ["This is a generation for the work" for i in range(2)],
        }
    ]
}
```
Results in 

```Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 122, in _process_request
    return_value = await method(*request.method_args, **request.method_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mlserver_huggingface/runtime.py", line 96, in predict
    prediction = self._model(*args, **kwargs)
TypeError: __call__() missing 1 required positional argument: 'inputs'
INFO:     172.17.0.1:34736 - "POST /v2/models/transformer/infer HTTP/1.1" 500 Internal Server Error
```

```
inference_request = {
    "inputs": [
        {
          "name": "inputs",
          "shape": [1],
          "datatype": "BYTES",
          "data": ["This is a generation for the work" for i in range(2)],
        }
    ]
}
```

Results in
```
  File "/opt/conda/lib/python3.8/site-packages/mlserver/parallel/worker.py", line 122, in _process_request
    return_value = await method(*request.method_args, **request.method_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mlserver_huggingface/runtime.py", line 96, in predict
    prediction = self._model(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/token_classification.py", line 212, in __call__
    _inputs, offset_mapping = self._args_parser(inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/token_classification.py", line 35, in __call__
    raise ValueError("At least one input is required.")
ValueError: At least one input is required.
INFO:     172.17.0.1:34926 - "POST /v2/models/transformer/infer HTTP/1.1" 500 Internal Server Error
```

**Comment by adriangonz** [comment]
Hey @ajsalow ,

Rather than an issue with batch, this feels more like a question about general usage of the Hugginface runtime.

The Huggingface runtime loads pipelines from the Huggingface Hub. Generally, the input names map 1:1 to the model arguments documented on the Huggingface docs. You will need to ensure the inputs match with what the underlying HF pipeline expects. Alternatively, you can also query the model's metadata to see the available inputs (reference for the Open Inference Protocol can be consulted [here](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/v2-protocol.html)).

For example, for the `text-generation` task, the available input is `array_inputs` - which takes your prompt texts and whose shape should look like `[-1, 1]`. 

On the point about that `TypeError` message, MLServer needs type hints to know how to handle payload data. This is generally handled through [Content Type](https://mlserver.readthedocs.io/en/latest/user-guide/content-type.html) annotations, which go either at the request level, or within the `model-settings.json` metadata. If you use the inputs exposed through the model's metadata, these should already be pre-annotated with the right content type.
